vim9script

if !exists('$MYVIMDIR')
  # Get the directory containing your .vimrc
  var $MYVIMDIR = fnamemodify($MYVIMRC, ':h')
endif

source $MYVIMDIR/vimrc.d/common.vim
source $MYVIMDIR/vimrc.d/plugins.vim
source $MYVIMDIR/vimrc.d/mappings.vim
source $MYVIMDIR/vimrc.d/appearance.vim

if has('win64')
  source $MYVIMDIR/vimrc.d/os.windows.vim
elseif has('osx')
  source $MYVIMDIR/vimrc.d/os.macos.vim
else
  source $MYVIMDIR/vimrc.d/os.linux.vim
endif

# Patch to unify bgcolor for number and fold column
highlight clear FoldColumn

