vim9script

if !exists('$MYVIMDIR')
  # Get the directory containing your .vimrc
  var $MYVIMDIR = fnamemodify($MYVIMRC, ':h')
endif

source $MYVIMDIR/vimrc.d/settings.vim
source $MYVIMDIR/vimrc.d/plugins.vim
source $MYVIMDIR/vimrc.d/mappings.vim
source $MYVIMDIR/vimrc.d/appearance.vim

if has('win64')
  source $MYVIMDIR/vimrc.d/os.windows.vim
elseif has('osx')
  source $MYVIMDIR/vimrc.d/os.macos.vim
else
  source $MYVIMDIR/vimrc.d/os.linux.vim
endif

source $MYVIMDIR/vimrc.d/autocmds.vim

# Patch to unify bgcolor for number and fold column
highlight clear FoldColumn

# vim: set ft=vim ts=2 sw=2 et :
