# vim: set ft=sh ts=4 sw=4 noet :
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Enable the subsequent settings only in interactive sessions
case $- in
	*i*) ;;
	*) return;;
esac


# #############################################################################
# User configuration
# #############################################################################
source ~/.config/bash/rc.sh

