# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
export PATH=$PATH:$HOME/bin

# -----------------------------------------------------------------------------
# TMUX (just login shells)
# -----------------------------------------------------------------------------
if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
	 exec tmux
fi

