# ----------------------------------------------------------
# Main Alacritty configuration
# ----------------------------------------------------------
[general]
working_directory = "$HOME/Documents/Projects"
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[window]
dimensions = { columns = 130, lines = 35 }
padding = { x = 5, y = 5 }
startup_mode = "Windowed"
decorations_theme_variant = "Dark"
decorations = "Full"
title = ""
option_as_alt = "OnlyLeft"

[scrolling]
history = 15000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = 'Regular' }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 20.0
offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = false

[env]
TERM_PROGRAM = "alacritty"
SHELL = "/usr/local/bin/fish"

[terminal.shell]
program = "/usr/local/bin/tmux"
args = ["new-session", "-A", "-s", "alacritty", "-e", "VIM_COLOR=tokyonight"]

[keyboard]
bindings = [
    # Chars
    { key = "Space",        mods = "Control",   chars = "\u0000" },
    { key = "Space",        mods = "Shift",     chars = "\u001B" },
    { key = "Slash",        mods = "Control",   chars = "\u001F" },
    { key = "Backslash",    mods = "Control",   chars = "\u002C" },
]
