# ----------------------------------------------------------
# Alacritty configuration
# https://alacritty.org/config-alacritty.html
#
# Themes: https://github.com/alacritty/alacritty-theme
# ----------------------------------------------------------
[general]
working_directory = "None"
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
]

[terminal.shell]
program = "pwsh"
args = ["-NoLogo"]

[env]
TERM_PROGRAM = "alacritty"

[window]
padding = { x = 5, y = 5 }
decorations = "Full"
startup_mode = "Windowed"
decorations_theme_variant = "None"
dimensions = { columns = 130, lines = 30 }
dynamic_title = false

[scrolling]
history = 15000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font Propo" }
size = 11.25

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [

    # Chars
    { key = "Space",        mods = "Control",   chars = "\u0000" },
    { key = "Space",        mods = "Shift",     chars = "\u001B" },
    { key = "Slash",        mods = "Control",   chars = "\u001F" },
    { key = "Backslash",    mods = "Control",   chars = "\u002C" },

    # Actions
    # { key = "Enter", mods = "Control|Shift", action = "ToggleMaximized" },
]

