# vim:fileencoding=utf-8:set ft=conf ts=2 sw=2 sts=2 et :
# ------------------------------------------------------------------
# https://sw.kovidgoyal.net/kitty/conf/
# ------------------------------------------------------------------

# What shell will be used
shell /usr/local/bin/bash --login

# Set Environment variables
env TERM_PROGRAM=kitty

# Map shift space to Esc
map shift+space send_text all \u001B

# Fonts
font_family       JetBrainsMonoNL Nerd Font Mono
font_size         18.0
bold_font         auto
italic_font       auto
bold_italic_font  auto

# Include files like themes
include current-theme.conf

