
# ------------------------------------------------------------------------------
# Status Bar
# Solarized colors
# ------------------------------------------------------------------------------
set -g status on
set -g status-position top
set -g status-bg colour234
set -g status-left-length 50
set -g status-justify centre
set -g status-left "#[fg=colour2] [ #S ] #[fg=colour6]|\ #[fg=colour3]• Window: #I • Pane: #P #[fg=colour6]| "
set -g status-fg colour10
set-window-option -g window-status-separator "#[fg=colour24] : "
set -g status-right "#[fg=colour6]|\ #[fg=colour2]%A, %B %d #[fg=colour6]|\ #[fg=colour7,bold]%H:%M\ "

# vim: set ft=tmux :
