
# ------------------------------------------------------------------------------
# Status Bar
# Blueish colors
# ------------------------------------------------------------------------------
set -g status on
set -g status-position top
set -g status-bg colour16 # <- status bar background
set -g status-left-length 50
set -g status-justify centre
set -g status-left "#[fg=blue] [ #S ] #[fg=white]|\ #[fg=blue]• Window: #I • Pane: #P #[fg=white]| "
set -g status-fg blue
set-window-option -g window-status-separator "#[fg=black] : "
set -g status-right "#[fg=white]|\ #[fg=colour4]%a %B %d #[fg=white,bold]|\ %H:%M\ "

# vim: set ft=tmux :
